# Generated by Django 2.2.9 on 2020-11-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='tb_projects',
        ),
    ]
